Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/BlockComments:
  Enabled: false
